# docker hub publish image CI using docker command which is already installed in ubuntu-latest
# using workflow_dispatch event and passing logLevel
name: Latest - Docker Image CI

on:
  # Create workflows that are manually triggered using below event:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'  
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Inputs
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"   
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Print version
        run: echo "Version ${{ steps.vars.outputs.tag }}"   
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag deepakgcsib/raml-mock-service:latest
      - name: Push the latest Docker image
        run: docker push deepakgcsib/raml-mock-service:latest
