name: Short Docker Image CI 

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: deepakgcsib/raml-mock-service
          repository: raml-mock-service
          tag_with_ref: true
