name: Short Docker Image CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        registry: deepakgcsib/raml-mock-service
        repository: raml-mock-service
        tags: v1
    - name: Build the Docker image
      
