# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
#   workflow_dispatch:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        #run: echo ::set-env name=tag::$(echo ${GITHUB_REF:10})
        run:  echo "tag=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Set tag to latest
        if: endsWith(github.ref, '/main')
        run: |
          echo "tag=latest" >> $GITHUB_ENV
      - name: Print tag name
        id: vars
        run: echo "$tag"    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: deepakgcsib/raml-mock-service:${{steps.vars.outputs.tag}}
